### ISSUE TITLE
how to use deployed in heroku.

### ISSUE THREAD

**Issue by jovvybersamin** [AstroCB/AssumeZero-Bot#21]
I deployed the bot in heroku app and also configured the variables.

And I also created a dummy GC and added the dummy FB account. After that what's next?

![configs](https://user-images.githubusercontent.com/8434972/91789210-c11a2680-ec40-11ea-889d-21dbe1af7527.png)

**Comment by AstroCB** [comment]
Is Is the bot running? You can use `(whatever trigger word you set) alive` to check. If not, check the logs in Heroku and see if there are any errors. You can find them in the menu in the top right (More > View logs).

**Comment by jovvybersamin** [comment]
Yeah, I think so, you can visit it here. 

https://messenger-bot-plus63.herokuapp.com/

**Comment by AstroCB** [comment]
Yep, looks like you're good to go. You can use `(trigger word) help` to see all the commands.

**Comment by jovvybersamin** [comment]
Do I need to add the Dummy Facebook Account to the private group chat first right?

**Comment by jovvybersamin** [comment]
I did, I tried the physics help (physics as a default trigger in the config.js) but nothing happens, and no logs from Heroku too.

**Comment by AstroCB** [comment]
Yeah you can either do that, or you can private message the dummy account directly. Did you set the Facebook email and password config vars to the dummy account's credentials?

**Comment by jovvybersamin** [comment]
Yeah, I did that but no response if I type "physics help". 
Do I have to change the owner and bot information in the config.js file?

**Comment by AstroCB** [comment]
You can, but it shouldn't make a difference here. Can you send a screenshot of the logs?

**Comment by jovvybersamin** [comment]
Here

![logs](https://user-images.githubusercontent.com/8434972/91792530-49e89080-ec48-11ea-81a6-dc63e8bd165b.png)

**Comment by AstroCB** [comment]
Hmm, that all looks right to me. No changes when you use any commands?

**Comment by jovvybersamin** [comment]
Yeah, it seems it's not listening to the chat messages.

**Comment by AstroCB** [comment]
That's very odd, since all of the logging seems to indicate you've logged in successfully.

The only thing I can think of is that the process manager I recently switched over to is interfering with Heroku (I haven't tried deploying there in quite a while). One thing you can try is opening `package.json` and changing the `start` script to run `node src/main.js` instead of PM2.

**Comment by jovvybersamin** [comment]
Still, nothing happens, check the log.

![logs](https://user-images.githubusercontent.com/8434972/91793429-bebcca00-ec4a-11ea-89f9-3e2ed1745902.png)

**Comment by AstroCB** [comment]
This seems silly, but are you sure you're messaging the right account? Like the one whose email is set as `FACEBOOK_EMAIL`?

**Comment by jovvybersamin** [comment]
Yeah, absolutely, that's the first thing I check.

**Comment by AstroCB** [comment]
That's really the only thing I can think of – looking at the logs and opening the status site it seems like everything is running the way it should. 

For some more complex debugging, you can open `src/main.js` and try to put some `console.log()` statements on lines 60 and 68 to see if the messages are being picked up. 

From the behavior you've described and the logs you've shown, the best diagnosis I have is that the messages aren't being received because you're messaging the wrong account, but if everything checks out there then I'm not sure what the issue could be.

**Comment by jovvybersamin** [comment]
The console.log works on lines 60 (I logged the handleMessage function) but for the line 68,
 it didn't get triggered.

![logs](https://user-images.githubusercontent.com/8434972/91796488-db5d0000-ec52-11ea-9a05-702c79023664.png)

**Comment by jovvybersamin** [comment]
Btw, I even created a new dummy FB account to test and I still didn't get any response nor any logs.

**Comment by AstroCB** [comment]
Yeah, so that confirms that the message handler isn't being called, which means the listener isn't picking up the message. Because you've logged in successfully and there aren't any errors in the logs, the only thing I can think that would cause that is that the messages aren't being sent to the account it's running on (assuming Facebook's backend hasn't broken the listener, which I can confirm from my own instance). 

The two things I would try are 1) try running the bot on your local machine instead of Heroku and if that doesn't work, 2) try looking at [facebook-chat-api](github.com/Schmavery/facebook-chat-api) and see if you can get the basic echo bot working on your dummy account.

**Comment by jovvybersamin** [comment]
It works when I used the **facebook-chat-api.**

Using this code.

```
login({ email: "myemail", password: "mypassword" }, (err, api) => {
    if (err) return console.error(err);

    api.setOptions({
        forceLogin: true
    });

    api.listenMqtt((err, message) => {
        api.sendMessage(message.body, message.threadID);
    });
});

```

**Comment by jovvybersamin** [comment]
Why I'm getting this error when running the your bot locally (windows 10)

```
[PM2] Done.
[PM2][ERROR] Script not found: D:\Projects\Hobby\MessengerBot\AssumeZero-Bot\run-script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! assumezero-bot@2.0.0 start: `pm2 start src/main.js --name 'assumezero-bot'; npm run-script logs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the assumezero-bot@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-09-01T15_06_29_169Z-debug.log
```

**Comment by AstroCB** [comment]
You'll probably want to alter `package.json` again and change it to be only `node src/main.js` (or maybe it'd be `src\main.js` on Windows? I'm not sure).

**Comment by AstroCB** [comment]
You'll probably want to run the bot using `node src\main.js` if you're using Windows. I've never tested it on Windows so I'm not sure whether it will work.

**Comment by jovvybersamin** [comment]
It works when I changed to "node src\main.js" but the same thing, it's not listening to any of my triggers.

```
$ npm start
assumezero-bot@2.0.0 start D:\Projects\Hobby\MessengerBot\AssumeZero-Bot
node src/main.js --name 'assumezero-bot'; npm run-script logs

Bot 100041587845629 logging in locally with trigger "physics".
Logging in with saved appstate...
Successfully logged in to user account 100054542996517.

```

**Comment by AstroCB** [comment]
It seems you're still running `npm start`, which I would not recommend on Windows, and you're also invoking other scripts which rely on PM2. I'd just run the node command directly in your terminal (or alternatively delete everything after the `node src/main.js` in the start script).

**Comment by jovvybersamin** [comment]
still not listening. do I have to explicitly set the thread/chat id?

**Comment by jovvybersamin** [comment]
I was able to make it work by creating a new MemCachier. Btw, unrelated to the issue, how I will tag all the members in the group chat?

**Comment by AstroCB** [comment]
Ah, interesting! Very odd that that's the case, and I do wonder why no issues showed up in the logs (typically memcache failures show up as disconnects in the logs), and why that log I asked you to put never fired since it doesn't rely on the memcache. Glad it's working for you now!

You can tag everyone in the group with `@@all`. Let me know if you run into any other issues!

**Comment by BotolMehedi** [comment]
@AstroCB 
![Screenshot_2021-05-01-15-49-07](https://user-images.githubusercontent.com/64999484/116778639-f5c2d400-aa94-11eb-829c-953059642b7d.png)
![Screenshot_2021-05-01-15-48-12](https://user-images.githubusercontent.com/64999484/116778646-f9565b00-aa94-11eb-8ed0-9fec9394801a.png)

How to solved this problem???
