### ISSUE TITLE
Problem with Heroku deployment

### ISSUE THREAD

**Issue by Smakuwa** [AstroCB/AssumeZero-Bot#51]
Okay, so I've read all the previous issues and fixed few things by myself, but I just don't understand why does it happen. May be my r e a l l y small experience here.

2021-03-17T09:40:02.600715+00:00 app[web.1]: 0|assumezero-bot  |   code: 'MODULE_NOT_FOUND',
2021-03-17T09:40:02.600809+00:00 app[web.1]: 0|assumezero-bot  |   path: '/app/node_modules/messenger-botcore/package.json',

![2021-03-17 10_42_18-C__WINDOWS_system32_cmd exe - heroku  logs --tail -a student-debil-bot](https://user-images.githubusercontent.com/45312377/111447209-7e67f980-870d-11eb-8a1c-3ccf844826fc.png)

**Comment by AstroCB** [comment]
👋 hey there!

Apologies for this – because of a bug with one of this package's upstream dependencies, I pinned the version of the package that imports it to the bleeding edge so that I could switch it back after the bug was fixed. I introduced a breaking change right around the time you were running it which got pulled down when you installed.

The change should be fixed on the AssumeZero-Bot side now, so try doing a fresh install from the current master and things should be good to go.
